import { useEffect, useRef, useState, type ReactNode } from 'react';
import { ledgerRpc, type LedgerWorkspace } from '../lib/ledgerRepository';
import { parseBrlCents } from '../../../shared/finance/money';

const panel='card p-5 dark:border-slate-800 dark:bg-slate-900',input='w-full field-input';
const field=(title:string,content:ReactNode)=><div className="grid gap-2 text-sm"><p>{title}</p>{content}</div>;
export default function LedgerPeople({workspace,money,onChanged,onAgenda}:{workspace:LedgerWorkspace;money:(value:number)=>string;onChanged:()=>Promise<void>;onAgenda:()=>void}) {
  const [person,setPerson]=useState<string|null>(null),[shared,setShared]=useState(false),[retry,setRetry]=useState(()=>crypto.randomUUID()),[selected,setSelected]=useState<string[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const canWrite=workspace.role!=='viewer',cash=workspace.accounts.filter(account=>account.liquidity==='cash');
  async function run(name:string,args:Record<string,unknown>) {setBusy(true);setError('');setNotice('');try {await ledgerRpc(name,{p_space:workspace.space.id,...args});await onChanged();setPerson(null);setShared(false);setSelected([]);setRetry(crypto.randomUUID());setNotice('Movimentação com pessoas registrada.');}catch(failure){setError(failure instanceof Error?failure.message:'Não foi possível salvar.');}finally{setBusy(false);}}
  return <div className="space-y-4">{error&&<p role="alert" className="rounded-xl bg-red-50 p-4 text-sm text-red-800 dark:bg-red-950 dark:text-red-200">{error}</p>}{notice&&<p role="status" className="text-sm text-brand-700 dark:text-brand-300">{notice}</p>}
    <section className={`${panel} space-y-4`}><h2 className="font-semibold">Valores com pessoas</h2><p className="max-w-prose text-sm text-slate-500">Recebimentos e pagamentos ajustam o saldo da pessoa. O valor que cabe aos outros em uma despesa compartilhada fica a receber.</p>{workspace.people.length===0&&<p className="text-sm text-slate-500">Use Cadastrar para adicionar uma pessoa.</p>}{workspace.people.map(item=><article key={item.id} className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 py-3 last:border-0 dark:border-slate-800"><div><h3 className="font-medium">{item.nickname}</h3><p className="text-sm text-slate-500">{item.balance_cents>0?'A receber':item.balance_cents<0?'A pagar':'Acertado'} · {money(Math.abs(item.balance_cents))}</p></div>{canWrite&&<button disabled={busy} onClick={()=>{setPerson(item.id);setShared(false);setRetry(crypto.randomUUID());setError('');}} className="text-sm font-semibold text-brand-700 dark:text-brand-300">Registrar recebimento ou pagamento</button>}</article>)}</section>
    {canWrite&&workspace.people.length>0&&<button disabled={busy} onClick={()=>{setShared(true);setPerson(null);setRetry(crypto.randomUUID());setSelected([]);setError('');}} className="btn-primary px-4 py-2.5 text-sm font-semibold text-white">Dividir uma despesa que eu paguei</button>}
    {canWrite&&(person||shared)&&<form key={`${person??'shared'}-${retry}`} onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget),text=(name:string)=>String(form.get(name)??'').trim();try {const amount=parseBrlCents(text('amount'));if(shared)void run('record_shared_expense',{p_account:text('account'),p_category:text('category'),p_people:selected,p_total_cents:amount,p_occurred_on:text('date'),p_description:text('description'),p_client_uuid:retry});else void run('settle_person',{p_person:person,p_account:text('account'),p_direction:text('direction'),p_amount_cents:amount,p_occurred_on:text('date'),p_client_uuid:retry});}catch(failure){setError((failure as Error).message);}}} className={`${panel} grid gap-4 sm:grid-cols-2`}>
      <h2 className="font-semibold sm:col-span-2">{shared?'Despesa dividida em partes iguais':`Movimentação com ${workspace.people.find(item=>item.id===person)?.nickname}`}</h2>
      {!shared&&field('Tipo de movimentação',<select name="direction" aria-label="Tipo de movimentação com pessoa" defaultValue={workspace.people.find(item=>item.id===person)!.balance_cents<0?'pay':'receive'} className={input}><option value="receive">Recebi o que a pessoa me devia</option><option value="pay">Paguei o que devia à pessoa</option><option value="lend">Emprestei dinheiro à pessoa</option><option value="borrow">Recebi dinheiro emprestado da pessoa</option></select>)}
      {field('Conta da movimentação',<select name="account" aria-label="Conta da movimentação com pessoa" required defaultValue="" className={input}><option value="">Selecione uma conta</option>{cash.map(account=><option key={account.id} value={account.id}>{account.name}</option>)}</select>)}{field(shared?'Valor total que eu paguei (R$)':'Valor da movimentação (R$)',<input name="amount" aria-label="Valor com pessoas (R$)" inputMode="decimal" required className={input}/>)}{field('Data',<input name="date" aria-label="Data da movimentação com pessoa" type="date" required defaultValue={workspace.space.today} className={input}/>)}
      {shared&&<>{field('Descrição',<input name="description" aria-label="Descrição da despesa dividida" required maxLength={100} className={input}/>)}{field('Categoria da minha parte',<select name="category" aria-label="Categoria da despesa dividida" required defaultValue="" className={input}><option value="">Selecione</option>{workspace.categories.filter(category=>category.kind==='expense'&&category.ledger_account_id).map(category=><option key={category.id} value={category.id}>{category.name}</option>)}</select>)}<fieldset className="space-y-2 sm:col-span-2"><legend className="mb-2 text-sm font-medium">Pessoas que dividem comigo</legend>{workspace.people.map(item=><label key={item.id} className="mr-4 inline-flex gap-2 text-sm"><input type="checkbox" checked={selected.includes(item.id)} onChange={event=>setSelected(ids=>event.target.checked?[...ids,item.id]:ids.filter(id=>id!==item.id))}/>{item.nickname}</label>)}<p className="text-xs text-slate-500">Você também participa da divisão. Somente a sua parte entra no consumo; a parte das pessoas fica a receber.</p></fieldset></>}
      <div className="flex gap-3 sm:col-span-2"><button disabled={busy||cash.length===0||shared&&selected.length===0} className="btn-primary px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">Confirmar movimentação com pessoas</button><button type="button" onClick={()=>{setPerson(null);setShared(false);}}>Cancelar</button></div>
    </form>}
    <PeopleManagement workspace={workspace} money={money} onAgenda={onAgenda} onChanged={async()=>{setPerson(null);setShared(false);await onChanged();}}/>
  </div>;
}

type Contact={id:string;nickname:string;notes:string|null;kind:string;version:number;archived_at:string|null;opening_on:string|null;balance_cents:number;scheduled_balance_cents:number};
type PersonDetail={person:Contact;balance_cents:number;movements:{id:string;occurred_on:string;description:string;status:string;person_amount_cents:number;running_balance_cents:number}[];reminders:{id:string;title:string;effective_due_on:string;completed_at:string|null}[]};
const displayDate=(value:string)=>value.split('-').reverse().join('/');

function PeopleManagement({workspace,money,onChanged,onAgenda}:{workspace:LedgerWorkspace;money:(value:number)=>string;onChanged:()=>Promise<void>;onAgenda:()=>void}) {
  const [contacts,setContacts]=useState<Contact[]>([]),[selected,setSelected]=useState(''),[includeArchived,setIncludeArchived]=useState(false),[detail,setDetail]=useState<PersonDetail|null>(null),[mode,setMode]=useState<'view'|'create'|'edit'|'opening'>('view'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const pending=useRef(false),request=useRef<{key:string;id:string}|null>(null);
  const canWrite=workspace.role!=='viewer',contact=contacts.find(item=>item.id===selected),visible=contacts.filter(item=>includeArchived||!item.archived_at);
  async function load(){const result=await ledgerRpc<{people:Contact[]}>('people_management_summary',{p_space:workspace.space.id,p_include_archived:true});setContacts(result.people);}
  useEffect(()=>{let stopped=false;setContacts([]);setDetail(null);void ledgerRpc<{people:Contact[]}>('people_management_summary',{p_space:workspace.space.id,p_include_archived:true}).then(result=>{if(!stopped)setContacts(result.people);}).catch(()=>{if(!stopped)setError('Não foi possível carregar os cadastros de pessoas.');});return()=>{stopped=true;};},[workspace]);
  useEffect(()=>{let stopped=false;setDetail(null);if(selected)void ledgerRpc<PersonDetail>('person_detail',{p_space:workspace.space.id,p_person:selected}).then(result=>{if(!stopped)setDetail(result);}).catch(()=>{if(!stopped)setError('Não foi possível carregar o histórico da pessoa.');});return()=>{stopped=true;};},[workspace,selected]);
  async function manage(action:string,changes:Record<string,unknown>={}) {
    if(pending.current)return;pending.current=true;setBusy(true);setError('');setNotice('');
    const args={p_space:workspace.space.id,p_person:action==='create'?null:contact?.id,p_version:action==='create'?null:contact?.version,p_action:action,p_changes:changes},key=JSON.stringify(args);
    if(request.current?.key!==key)request.current={key,id:crypto.randomUUID()};
    try{const id=await ledgerRpc<string>('manage_person',{...args,p_client_uuid:request.current.id});setMode('view');setSelected(action==='delete'||action==='archive'&&!includeArchived?'':id);await load();await onChanged();request.current=null;setNotice(action==='archive'?'Pessoa arquivada. Seu histórico e lembretes foram preservados.':action==='delete'?'Contato excluído.':action==='opening'?'Saldo inicial registrado sem alterar receitas e despesas.':'Cadastro salvo.');}
    catch(failure){const text=failure instanceof Error?failure.message:'';setError(text.includes('changed; reload')?'Esse cadastro mudou. Atualize a página antes de tentar novamente.':text.includes('including scheduled')?'Acerte o saldo atual e os movimentos agendados antes de arquivar.':text.includes('unused and unlinked')?'A pessoa tem histórico ou vínculos. Use arquivar depois de acertar o saldo.':text.includes('unused contact')?'O saldo inicial só pode ser informado para um contato sem movimentos.':text.includes('month is closed')?'Reabra o mês antes de registrar o saldo inicial.':text.includes('Active member')?'A pessoa representa um membro ativo. Gerencie a saída em Compartilhamento.':'Não foi possível salvar. Confira os dados e tente novamente.');}
    finally{pending.current=false;setBusy(false);}
  }
  return <section className={`${panel} space-y-4`} aria-label="Cadastro e histórico de pessoas">
    <div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-semibold">Cadastro e histórico de pessoas</h2>{canWrite&&<button disabled={busy} onClick={()=>{setMode('create');setSelected('');setError('');request.current=null;}} className="rounded-xl bg-brand-700 px-4 py-2 text-sm font-semibold text-white">Adicionar pessoa</button>}</div>
    <p className="max-w-prose text-sm text-slate-500">Comece pelo apelido. Se já existe um valor a receber ou pagar, informe o saldo inicial depois de salvar o contato.</p>
    {error&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-800 dark:bg-red-950 dark:text-red-200">{error}</p>}{notice&&<p role="status" className="text-sm text-brand-700 dark:text-brand-300">{notice}</p>}
    <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={includeArchived} onChange={event=>{setIncludeArchived(event.target.checked);if(!event.target.checked&&contact?.archived_at){setSelected('');setMode('view');}}}/>Incluir pessoas arquivadas</label>
    <label className="grid gap-2 text-sm">Consultar pessoa<select aria-label="Consultar pessoa" value={selected} onChange={event=>{setSelected(event.target.value);setMode('view');setError('');request.current=null;}} className={input}><option value="">Selecione um contato</option>{visible.map(item=><option key={item.id} value={item.id}>{item.nickname}{item.archived_at?' · arquivada':''}</option>)}</select></label>
    {canWrite&&(mode==='create'||mode==='edit')&&<form key={`${mode}-${contact?.id??'new'}-${contact?.version??0}`} onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);void manage(mode==='create'?'create':'update',{nickname:String(form.get('nickname')??'').trim(),notes:String(form.get('notes')??'').trim()||null});}} className="grid gap-4 sm:grid-cols-2">
      <label className="grid gap-2 text-sm">Apelido<input aria-label="Apelido da pessoa" name="nickname" required maxLength={100} defaultValue={mode==='edit'?contact?.nickname:''} className={input}/></label>
      <label className="grid gap-2 text-sm">Observações opcionais<textarea aria-label="Observações da pessoa" name="notes" maxLength={2000} defaultValue={mode==='edit'?contact?.notes??'':''} className={input}/></label>
      <div className="flex gap-3 sm:col-span-2"><button disabled={busy} className="rounded-xl bg-brand-700 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">Salvar pessoa</button><button type="button" onClick={()=>setMode('view')}>Cancelar</button></div>
    </form>}
    {contact&&mode!=='create'&&<div className="space-y-4">
      <p className="font-medium">{contact.balance_cents>0?`${contact.nickname} te deve ${money(contact.balance_cents)}`:contact.balance_cents<0?`Você deve ${money(-contact.balance_cents)} a ${contact.nickname}`:'Em dia'}{contact.archived_at?' · arquivada':''}</p>
      {contact.notes&&<p className="whitespace-pre-wrap text-sm text-slate-500">{contact.notes}</p>}
      {contact.scheduled_balance_cents!==0&&<p className="text-sm text-slate-500">Movimentos futuros: {money(contact.scheduled_balance_cents)}.</p>}
      {canWrite&&<div className="flex flex-wrap gap-4 text-sm font-semibold text-brand-700 dark:text-brand-300">{!contact.archived_at?<>
        <button disabled={busy} onClick={()=>setMode('edit')}>Editar apelido e observações</button>
        {contact.kind==='contact'&&contact.opening_on===null&&detail?.movements.length===0&&<button disabled={busy} onClick={()=>setMode('opening')}>Informar saldo inicial</button>}
        {contact.kind!=='member'&&<button disabled={busy} onClick={()=>void manage('archive')}>Arquivar pessoa</button>}
      </>:<button disabled={busy} onClick={()=>void manage('restore')}>Desarquivar pessoa</button>}{contact.kind==='contact'&&detail?.movements.length===0&&detail.reminders.length===0&&<button disabled={busy} onClick={()=>void manage('delete')} className="text-red-700 dark:text-red-300">Excluir contato sem uso</button>}</div>}
      {canWrite&&mode==='opening'&&<form onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);try{const amount=parseBrlCents(String(form.get('amount')??''));if(amount<0)throw new Error('Use um valor positivo e escolha quem deve.');void manage('opening',{balance_cents:form.get('direction')==='pay'?-amount:amount,on:String(form.get('date'))});}catch(failure){setError(failure instanceof Error?failure.message:'Confira o valor.');}}} className="grid gap-4 sm:grid-cols-2">
        <label className="grid gap-2 text-sm">Quem deve<select aria-label="Direção do saldo inicial da pessoa" name="direction" className={input}><option value="receive">A pessoa me deve</option><option value="pay">Eu devo à pessoa</option></select></label><label className="grid gap-2 text-sm">Saldo inicial (R$)<input aria-label="Saldo inicial da pessoa (R$)" name="amount" inputMode="decimal" required className={input}/></label><label className="grid gap-2 text-sm">Data do início<input aria-label="Data do saldo inicial da pessoa" name="date" type="date" required defaultValue={workspace.space.today} max={workspace.space.today} className={input}/></label>
        <p className="text-xs text-slate-500">Esse valor representa uma dívida que já existia. Ele entra contra Abertura e fica fora de receitas, despesas e saldo em contas.</p><div className="flex gap-3 sm:col-span-2"><button disabled={busy} className="rounded-xl bg-brand-700 px-4 py-2 text-sm font-semibold text-white">Registrar saldo inicial</button><button type="button" onClick={()=>setMode('view')}>Cancelar</button></div>
      </form>}
      <div className="space-y-2"><h3 className="text-sm font-semibold">Movimentos</h3>{!detail?<p className="text-sm text-slate-500">Carregando histórico…</p>:detail.movements.length===0?<p className="text-sm text-slate-500">Nenhum movimento com esta pessoa.</p>:detail.movements.map(item=><div key={item.id} className="flex flex-wrap justify-between gap-2 border-b border-slate-100 py-2 text-sm dark:border-slate-800"><div><p>{item.description}{item.status==='cancelled'?' · cancelado':item.occurred_on>workspace.space.today?' · agendado':''}</p><p className="text-xs text-slate-500">{displayDate(item.occurred_on)}</p></div><div className="text-right"><p>{money(item.person_amount_cents)}</p><p className="text-xs text-slate-500">Saldo após o movimento: {money(item.running_balance_cents)}</p></div></div>)}</div>
      <div className="space-y-2"><h3 className="text-sm font-semibold">Lembretes da Agenda</h3>{detail?.reminders.map(item=><p key={item.id} className="text-sm text-slate-500">{displayDate(item.effective_due_on)} · {item.title}{item.completed_at?' · concluído':''}</p>)}{detail?.reminders.length===0&&<p className="text-sm text-slate-500">Nenhum lembrete ligado a esta pessoa.</p>}<button onClick={onAgenda} className="inline-block text-sm font-semibold text-brand-700 dark:text-brand-300">Abrir Agenda</button></div>
    </div>}
  </section>;
}
