import { cloneElement, Fragment, isValidElement, useEffect, useRef, useState, type ReactElement, type FormEvent, type ReactNode } from 'react';
import { ledgerRpc, type LedgerWorkspace } from '../lib/ledgerRepository';
import { parseBrlCents } from '../../../shared/finance/money';

interface AgendaItem { id: string; type: string; title: string; on: string; nominal_due_on?: string; competence_month?: string; due_amount_cents?: number; remaining_cents: number | null; paid_cents?: number; direction: string | null; certainty?: string; settlement_status: string; version: number; category_id?: string | null; category_name?: string; notes?: string | null; payment_name?: string; payment_method?: string; payment_financial_account_id?: string; payment_credit_card_id?: string; loan_installment?: boolean; reserve_id?: string; recurrence_rule_id?: string }
interface Calendar { month: string; today: string; items: AgendaItem[] }
const input = 'w-full min-w-0 field-input';
const panel = 'card p-4 sm:p-5';
const primary = 'btn-primary px-4 py-2.5 text-sm font-semibold disabled:opacity-50';
const secondary = 'text-slate-500 dark:text-slate-400';
const field = (name: string, content: ReactNode, width = 'sm:w-44') => <label key={name} className={`grid w-full min-w-0 gap-1.5 ${width}`}><span className="field-label">{name}</span>{isValidElement(content) ? cloneElement(content as ReactElement<{ 'aria-label'?: string }>, { 'aria-label': name }) : content}</label>;
const decimal = (value: number) => `${Math.floor(value / 100)},${String(value % 100).padStart(2, '0')}`;
const dateLabel = (date: string) => date.split('-').reverse().join('/');
const statuses: Record<string, string> = { settled: 'Concluído', cancelled: 'Cancelado', partial: 'Parcial', pending: 'Pendente', scheduled: 'Agendado' };
const itemTypes: Record<string, string> = { one_off: 'Compromisso', occurrence: 'Recorrência', reminder: 'Lembrete', card_statement: 'Fatura', scheduled_transaction: 'Lançamento futuro' };
const itemKey = (item: AgendaItem) => `${item.type}-${item.id}`;

export default function LedgerAgenda({ workspace, money, onChanged }: { workspace: LedgerWorkspace; money: (value: number) => string; onChanged: () => Promise<void> }) {
  const [month, setMonth] = useState(workspace.space.today.slice(0, 7)), [calendar, setCalendar] = useState<Calendar | null>(null), [day, setDay] = useState(''), [status, setStatus] = useState('open');
  const [creationKind, setCreationKind] = useState('one_off'), [direction, setDirection] = useState('outflow'), [creationMethod, setCreationMethod] = useState('account');
  const [details, setDetails] = useState<string | null>(null), [action, setAction] = useState<{ id: string; type: 'pay' | 'edit' | 'cancel' } | null>(null), [method, setMethod] = useState('account'), [retry, setRetry] = useState(() => crypto.randomUUID());
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState('');
  const pending = useRef(false), paymentRequests = useRef(new Map<string, string>());
  const canWrite = workspace.role !== 'viewer';
  async function load() { setCalendar(await ledgerRpc<Calendar>('agenda_month', { p_space: workspace.space.id, p_month: `${month}-01` })); }
  useEffect(() => { let active = true; setCalendar(previous => previous?.month === `${month}-01` ? previous : null); void ledgerRpc<Calendar>('agenda_month', { p_space: workspace.space.id, p_month: `${month}-01` }).then(next => { if (active) setCalendar(next); }).catch(failure => { if (active) setError(failure.message); }); return () => { active = false; }; }, [workspace, month]);
  async function run(name: string, args: Record<string, unknown>, onSaved?: () => void) {
    if (pending.current) return;
    pending.current = true; setBusy(true); setError(''); setNotice('');
    let saved = false;
    try {
      const { p_client_uuid: suppliedId, ...payload } = args;
      const paymentKey = name === 'settle_commitment' ? JSON.stringify(payload) : null;
      if (paymentKey && !paymentRequests.current.has(paymentKey)) paymentRequests.current.set(paymentKey, typeof suppliedId === 'string' ? suppliedId : crypto.randomUUID());
      await ledgerRpc(name, { p_space: workspace.space.id, ...args, ...(paymentKey ? { p_client_uuid: paymentRequests.current.get(paymentKey) } : {}) });
      if (paymentKey) paymentRequests.current.delete(paymentKey);
      saved = true; setAction(null); onSaved?.(); setNotice(name === 'create_commitment' ? 'Item adicionado à Agenda.' : 'Agenda atualizada.');
      await load(); await onChanged();
    } catch (failure) { setError(saved ? 'A alteração foi salva. Use Atualizar para recarregar a Agenda.' : failure instanceof Error ? failure.message : 'Não foi possível salvar.'); }
    finally { pending.current = false; setBusy(false); }
  }
  async function create(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (pending.current) return;
    const element = event.currentTarget, form = new FormData(element), text = (key: string) => String(form.get(key) ?? '').trim();
    const account = workspace.accounts.find(item => item.id === text('account'));
    try {
      const amount = creationKind === 'reminder' ? null : parseBrlCents(text('amount'));
      if (amount !== null && amount <= 0) throw new Error('O valor deve ser maior que zero.');
      await run('create_commitment', { p_payload: creationKind === 'reminder' ? { kind: 'reminder', title: text('name'), due_on: text('date'), person_id: text('person') } : { title: text('name'), direction: text('kind'), certainty: text('certainty'), amount_cents: amount, due_on: text('date'), competence_month: `${text('competence')}-01`, category_id: text('category'), payment_method: text('kind') === 'inflow' ? 'account' : creationMethod, payment_financial_account_id: text('kind') === 'inflow' || creationMethod === 'account' ? account?.id : null, payment_credit_card_id: text('kind') !== 'inflow' && creationMethod === 'card' ? text('card') : null } }, () => { element.reset(); setCreationKind('one_off'); setDirection('outflow'); setCreationMethod('account'); });
    } catch (failure) { setError(failure instanceof Error ? failure.message : 'Confira os campos.'); }
  }
  function choose(item: AgendaItem, type: 'pay' | 'edit' | 'cancel') { setDetails(itemKey(item)); setAction({ id: item.id, type }); setMethod(item.payment_method ?? 'account'); setRetry(crypto.randomUUID()); setError(''); setNotice(''); }
  async function payIntegral(item: AgendaItem) {
    await run('settle_commitment', { p_commitment: item.id, p_amount_cents: item.remaining_cents, p_on: workspace.space.today, p_client_uuid: crypto.randomUUID() });
  }
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const item = calendar?.items.find(row => row.id === action?.id); if (!item || !action || pending.current) return;
    const form = new FormData(event.currentTarget), text = (key: string) => String(form.get(key) ?? '').trim();
    try {
      if (action.type === 'pay') await run('settle_commitment', { p_commitment: item.id, p_amount_cents: parseBrlCents(text('amount')), p_on: text('date'), p_mode: text('mode'), p_client_uuid: retry });
      else if (action.type === 'cancel') await run('cancel_commitment', { p_commitment: item.id, p_version: item.version, p_reason: text('reason') });
      else await run('edit_commitment', { p_commitment: item.id, p_version: item.version, p_changes: { title: text('title'), notes: text('notes') || null, ...(item.type === 'reminder' || item.loan_installment || item.reserve_id || (item.paid_cents ?? 0) > 0 ? {} : { amount_cents: parseBrlCents(text('amount')), due_on: text('date'), competence_month: `${text('competence')}-01`, certainty: text('certainty'), category_id: text('category') || null, payment_method: method, payment_financial_account_id: method === 'account' ? text('account') : null, payment_credit_card_id: method === 'card' ? text('card') : null }) } });
    } catch (failure) { setError(failure instanceof Error ? failure.message : 'Confira os campos.'); }
  }
  const selected = calendar?.items.find(item => item.id === action?.id);
  const items = calendar?.items.filter(item => (!day || item.on === day) && (status === 'all' || status === 'settled' ? status === 'all' || item.settlement_status === 'settled' : ['pending', 'partial', 'scheduled'].includes(item.settlement_status))) ?? [];
  const [year, monthNumber] = month.split('-').map(Number), firstDay = (new Date(Date.UTC(year, monthNumber - 1, 1)).getUTCDay() + 6) % 7, days = new Date(Date.UTC(year, monthNumber, 0)).getUTCDate();
  const grouped = new Map<string, AgendaItem[]>(); for (const item of calendar?.items ?? []) if (item.settlement_status !== 'cancelled') grouped.set(item.on, [...(grouped.get(item.on) ?? []), item]);
  const editor = canWrite && action && selected && <form key={`${selected.id}-${action.type}`} aria-label={`${action.type === 'pay' ? 'Pagamento' : action.type === 'edit' ? 'Edição' : 'Cancelamento'} do item ${selected.title}`} onSubmit={event => void submit(event)} onChange={() => setRetry(crypto.randomUUID())}>
    <fieldset disabled={busy} className="grid min-w-0 gap-4 sm:grid-cols-2">
      <h3 className="min-w-0 font-semibold [overflow-wrap:anywhere] sm:col-span-2">{action.type === 'pay' ? selected.direction === 'inflow' ? 'Registrar recebimento' : 'Registrar pagamento' : action.type === 'edit' ? 'Editar somente este item' : 'Cancelar compromisso'}: {selected.title}</h3>
      {action.type === 'pay' && <>{field('Valor recebido ou pago (R$)', <input name="amount" inputMode="decimal" defaultValue={decimal(selected.remaining_cents ?? 0)} required className={input}/>, '')}{field('Data da movimentação', <input name="date" type="date" defaultValue={workspace.space.today} required className={input}/>, '')}{field('Como tratar a diferença', <select name="mode" className={input}><option value="partial">Pagamento parcial: manter o restante em aberto</option>{!selected.loan_installment && <><option value="match_actual">Quitar: confirmar este como o valor real</option><option value="automatic">Aplicar a regra do valor estimado</option></>}</select>, '')}<p className={`text-sm ${secondary}`}>Conta de pagamento: {selected.payment_name ?? 'Configurada no compromisso'}. Para escolher outra conta, edite o item antes de pagar.</p></>}
      {action.type === 'cancel' && <>{field('Motivo do cancelamento', <textarea name="reason" required maxLength={1000} className={input}/>, '')}<p className={`text-sm ${secondary}`}>O compromisso fica preservado no histórico. Pagamentos vinculados precisam ser cancelados antes.</p></>}
      {action.type === 'edit' && <>{field('Descrição do item', <input name="title" defaultValue={selected.title} maxLength={100} required className={input}/>, '')}{field('Observações', <textarea name="notes" defaultValue={selected.notes ?? ''} maxLength={1000} className={input}/>, '')}{selected.type !== 'reminder' && !selected.loan_installment && !selected.reserve_id && !(selected.paid_cents! > 0) ? <>
        {field('Valor previsto (R$)', <input name="amount" defaultValue={decimal(selected.due_amount_cents ?? 0)} inputMode="decimal" required className={input}/>, '')}{field('Vencimento nominal', <input name="date" type="date" defaultValue={selected.nominal_due_on ?? selected.on} required className={input}/>, '')}{field('Mês de competência', <input name="competence" type="month" defaultValue={selected.competence_month?.slice(0, 7) ?? month} required className={input}/>, '')}{field('Certeza do valor', <select name="certainty" defaultValue={selected.certainty} className={input}><option value="confirmed">Confirmado</option><option value="estimated">Estimado</option>{selected.direction === 'inflow' && <option value="conditional">Condicional</option>}</select>, '')}
        {field('Categoria deste item', <select name="category" defaultValue={selected.category_id ?? ''} className={input}><option value="">Manter a contrapartida atual</option>{workspace.categories.filter(category => category.ledger_account_id && category.kind === (selected.direction === 'inflow' ? 'income' : 'expense')).map(category => <option key={category.id} value={category.id}>{category.name}</option>)}</select>, '')}{field('Meio de pagamento', <select value={method} onChange={event => setMethod(event.target.value)} className={input}><option value="account">Conta</option>{selected.direction !== 'inflow' && <option value="card">Cartão</option>}</select>, '')}
        {method === 'account' ? field('Conta para o item', <select name="account" defaultValue={selected.payment_financial_account_id} required className={input}>{workspace.accounts.map(account => <option key={account.id} value={account.id}>{account.name}</option>)}</select>, '') : field('Cartão para o item', <select name="card" defaultValue={selected.payment_credit_card_id} required className={input}>{workspace.cards.map(card => <option key={card.id} value={card.id}>{card.name}</option>)}</select>, '')}
      </> : <p className={`text-sm ${secondary} sm:col-span-2`}>{selected.loan_installment ? 'A data e os valores desta parcela são corrigidos no cronograma do empréstimo, em Patrimônio.' : selected.reserve_id ? 'A data e o valor são corrigidos na provisão vinculada.' : selected.type === 'reminder' ? 'Este lembrete não gera movimentação financeira.' : 'Para mudar os termos financeiros, cancele primeiro os pagamentos vinculados.'}</p>}</>}
      <div className="flex flex-wrap items-center gap-3 sm:col-span-2"><button className={primary}>{busy ? 'Salvando…' : 'Confirmar'}</button><button type="button" onClick={() => setAction(null)} className={`text-sm ${secondary}`}>Voltar à Agenda</button></div>
    </fieldset>
  </form>;
  return <div className="min-w-0 space-y-4">
    {error && <p role="alert" className="rounded-xl border border-red-300 bg-red-50 p-4 text-sm text-red-800 dark:bg-red-950 dark:text-red-200">{error}</p>}{notice && <p role="status" className="text-sm text-brand-700 dark:text-brand-300">{notice}</p>}
    {canWrite && <form aria-label="Adicionar item à Agenda" onSubmit={event => void create(event)} className={panel}>
      <fieldset disabled={busy} className="flex min-w-0 flex-wrap items-end gap-3">
        {field('Nome ou descrição', <input name="name" required maxLength={100} placeholder="Ex: Aluguel" className={input}/>, 'sm:w-56')}
        {field('Tipo de item da Agenda', <select value={creationKind} onChange={event => setCreationKind(event.target.value)} className={input}><option value="one_off">Compromisso a pagar ou receber</option><option value="reminder">Lembrete ligado a uma pessoa</option></select>, 'sm:w-64')}
        {creationKind === 'reminder' ? field('Pessoa do lembrete', <select name="person" required defaultValue="" className={input}><option value="">Selecione uma pessoa</option>{workspace.people.map(person => <option key={person.id} value={person.id}>{person.nickname}</option>)}</select>, 'sm:w-52') : <>
          {field('Direção', <select name="kind" value={direction} onChange={event => setDirection(event.target.value)} className={input}><option value="outflow">A pagar</option><option value="inflow">A receber</option></select>, 'sm:w-32')}
          {field('Valor previsto', <select name="certainty" className={input}><option value="confirmed">Confirmado</option><option value="estimated">Estimado</option>{direction === 'inflow' && <option value="conditional">Condicional</option>}</select>, 'sm:w-36')}
          {direction !== 'inflow' && field('Meio de pagamento do compromisso', <select value={creationMethod} onChange={event => setCreationMethod(event.target.value)} className={input}><option value="account">Conta</option><option value="card">Cartão</option></select>, 'sm:w-52')}
          {creationMethod === 'account' || direction === 'inflow' ? field('Conta', <select name="account" required defaultValue="" className={input}><option value="" disabled>Selecione uma conta</option>{workspace.accounts.map(account => <option key={account.id} value={account.id}>{account.name}</option>)}</select>, 'sm:w-52') : field('Cartão do compromisso', <select name="card" required defaultValue="" className={input}><option value="">Selecione</option>{workspace.cards.map(card => <option key={card.id} value={card.id}>{card.name}</option>)}</select>, 'sm:w-52')}
          {field('Categoria', <select key={direction} name="category" required defaultValue="" className={input}><option value="" disabled>Selecione uma categoria</option>{workspace.categories.filter(category => category.ledger_account_id && category.kind === (direction === 'inflow' ? 'income' : 'expense')).map(category => <option key={category.id} value={category.id}>{category.name}</option>)}</select>, 'sm:w-52')}
          {field('Valor (R$)', <input name="amount" inputMode="decimal" placeholder="0,00" required className={input}/>, 'sm:w-32')}
          {field('Competência do compromisso', <input name="competence" type="month" defaultValue={workspace.space.today.slice(0, 7)} required className={input}/>, 'sm:w-52')}
        </>}
        {field('Vencimento', <input name="date" type="date" defaultValue={workspace.space.today} required className={input}/>, 'sm:w-44')}
        <button className={`${primary} w-full sm:w-auto`}>{busy ? 'Salvando…' : 'Adicionar item'}</button>
      </fieldset>
    </form>}
    <section className={`${panel} space-y-4`} aria-label="Filtros da Agenda"><div className="flex min-w-0 flex-wrap items-end gap-3">
      {field('Mês da Agenda', <input type="month" value={month} disabled={busy} onChange={event => { if (event.target.value) { setMonth(event.target.value); setDay(''); setAction(null); setDetails(null); setError(''); } }} required className={input}/>)}
      {field('Situação', <select value={status} disabled={busy} onChange={event => { setStatus(event.target.value); setAction(null); setDetails(null); }} className={input}><option value="open">Pendentes e agendados</option><option value="settled">Concluídos</option><option value="all">Todos</option></select>, 'sm:w-52')}
      <button disabled={busy} onClick={() => { setDay(''); setAction(null); setDetails(null); }} className="py-2.5 text-sm font-semibold text-brand-700 dark:text-brand-300">Ver o mês inteiro</button>
    </div>
      <details className="border-t border-slate-200 pt-3 dark:border-slate-800"><summary className="cursor-pointer text-sm font-semibold">Calendário do mês</summary>
        <div className="mt-3 grid grid-cols-7 gap-1 text-center text-xs">{['Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb', 'Dom'].map(label => <span key={label} className={`py-2 ${secondary}`}>{label}</span>)}{Array.from({ length: firstDay }, (_, index) => <span key={`blank-${index}`}/>)}{Array.from({ length: days }, (_, index) => { const on = `${month}-${String(index + 1).padStart(2, '0')}`, rows = grouped.get(on) ?? [], overdue = rows.some(item => ['pending', 'partial'].includes(item.settlement_status) && on < workspace.space.today); return <button key={on} aria-label={`${index + 1}: ${rows.length} itens`} aria-pressed={day === on} onClick={() => { setDay(day === on ? '' : on); setAction(null); setDetails(null); }} className={`min-h-16 min-w-0 rounded-lg border p-1 sm:min-h-20 ${day === on ? 'border-brand-600 bg-brand-50 dark:bg-brand-950' : 'border-slate-200 dark:border-slate-800'} ${on === workspace.space.today ? 'font-bold ring-1 ring-brand-500' : ''}`}><span>{index + 1}</span>{rows.length > 0 && <span className={`mt-2 block rounded-full px-0.5 py-0.5 text-[10px] ${overdue ? 'bg-red-100 text-red-800 dark:bg-red-950 dark:text-red-200' : 'bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-300'}`}>{rows.length}<span className="hidden sm:inline"> {rows.length === 1 ? 'item' : 'itens'}</span></span>}</button>; })}</div>
        <p className={`mt-3 text-xs ${secondary}`}>O calendário reúne compromissos, lembretes, faturas e lançamentos com data futura. Selecione um dia para ver os detalhes.</p>
      </details>
    </section>
    <div className="table-shell"><table aria-label="Itens da Agenda" className="w-full table-fixed text-sm text-slate-900 dark:text-slate-100">
      <thead className="table-head uppercase tracking-wide"><tr><th scope="col" className="hidden w-[12%] px-4 py-2.5 sm:table-cell">Vencimento</th><th scope="col" className="w-[42%] px-3 py-2.5 sm:w-[34%] sm:px-4">{day ? `Itens de ${dateLabel(day)}` : 'Item'}</th><th scope="col" className="w-[32%] px-2 py-2.5 text-right sm:w-[20%] sm:px-4">Valor</th><th scope="col" className="hidden w-[18%] px-4 py-2.5 sm:table-cell">Situação</th><th scope="col" className="w-[26%] px-2 py-2.5 sm:w-[16%] sm:px-4"><span className="sr-only">Ações</span></th></tr></thead>
      <tbody className="divide-y divide-slate-100 dark:divide-slate-800">{items.map(item => <Fragment key={itemKey(item)}>
        <tr className="table-row-hover"><td className={`hidden px-4 py-2.5 ${secondary} sm:table-cell`}>{dateLabel(item.on)}</td><td className="px-3 py-2.5 [overflow-wrap:anywhere] sm:px-4"><span className="font-medium">{item.title}</span><p className={`mt-1 text-xs ${secondary}`}>{itemTypes[item.type] ?? 'Item'}{item.category_name ? ` · ${item.category_name}` : ''}</p><p className={`mt-1 text-xs ${secondary} sm:hidden`}>{dateLabel(item.on)} · {statuses[item.settlement_status] ?? item.settlement_status}</p>{['pending', 'partial'].includes(item.settlement_status) && item.on < workspace.space.today && <p className="mt-1 text-xs text-red-600 dark:text-red-400">Vencido</p>}</td><td className="px-2 py-2.5 text-right [overflow-wrap:anywhere] sm:px-4">{item.remaining_cents === null ? <span className={secondary}>Sem valor</span> : <><span className={`block text-xs ${secondary}`}>{item.direction === 'inflow' ? 'A receber' : 'A pagar'}</span><strong className="font-semibold">{money(item.remaining_cents)}</strong></>}</td><td className={`hidden px-4 py-2.5 text-xs ${secondary} sm:table-cell`}>{statuses[item.settlement_status] ?? item.settlement_status}</td><td className="px-2 py-2.5 text-right sm:px-4"><button type="button" disabled={busy} aria-label={`Detalhes do item ${item.title}`} aria-expanded={details === itemKey(item)} onClick={() => { setDetails(details === itemKey(item) ? null : itemKey(item)); setAction(null); }} className="text-xs font-semibold text-brand-700 dark:text-brand-400">{details === itemKey(item) ? 'Fechar' : 'Detalhes'}</button></td></tr>
        {details === itemKey(item) && <tr><td colSpan={5} className="p-3 sm:p-4"><section aria-label={`Detalhes do item ${item.title}`} className={`${panel} min-w-0 space-y-4 [overflow-wrap:anywhere]`}><div><h2 className="font-semibold">{item.title}</h2><p className={`mt-1 text-xs ${secondary}`}>{dateLabel(item.on)} · {statuses[item.settlement_status] ?? item.settlement_status}{item.category_name ? ` · ${item.category_name}` : ''}{item.payment_name ? ` · ${item.payment_name}` : ''}</p>{item.paid_cents !== undefined && item.paid_cents > 0 && <p className={`mt-2 text-sm ${secondary}`}>Já recebido ou pago: {money(item.paid_cents)}</p>}{item.notes && <p className={`mt-2 whitespace-pre-wrap text-sm ${secondary}`}>{item.notes}</p>}</div>
          {item.type === 'card_statement' && <p className={`text-xs ${secondary}`}>Pagamento e detalhes da fatura estão em Cartões.</p>}{item.type === 'scheduled_transaction' && <p className={`text-xs ${secondary}`}>Movimentação registrada com data futura. Consulte os detalhes em Lançamentos.</p>}
          {canWrite && ['one_off', 'occurrence', 'reminder'].includes(item.type) && item.settlement_status !== 'cancelled' && <div className="flex flex-wrap gap-3 text-sm font-semibold text-brand-700 dark:text-brand-300">{item.type === 'reminder' ? <button disabled={busy} onClick={() => void run('complete_reminder', { p_commitment: item.id, p_version: item.version, p_completed: item.settlement_status !== 'settled' })}>{item.settlement_status === 'settled' ? 'Reabrir lembrete' : 'Concluir lembrete'}</button> : ['pending', 'partial'].includes(item.settlement_status) && <><button disabled={busy} onClick={() => void payIntegral(item)}>{item.direction === 'inflow' ? 'Registrar recebimento integral' : 'Registrar pagamento integral'}</button><button disabled={busy} onClick={() => choose(item, 'pay')}>Informar valor e data</button></>}<button disabled={busy} onClick={() => choose(item, 'edit')}>Editar este item</button>{!item.loan_installment && <button disabled={busy} onClick={() => choose(item, 'cancel')} className="text-red-600 dark:text-red-400">Cancelar item</button>}</div>}
          {action?.id === item.id && editor}
        </section></td></tr>}
      </Fragment>)}{!items.length && <tr><td colSpan={5} className={`px-4 py-6 text-center ${secondary}`}>{!calendar ? 'Carregando Agenda…' : 'Nenhum item para este período e situação.'}</td></tr>}</tbody>
    </table></div>
  </div>;
}
