import { cloneElement, isValidElement, useEffect, useState, type ReactElement, type FormEvent, type ReactNode } from 'react';
import { ledgerRpc, type LedgerWorkspace } from '../lib/ledgerRepository';
import { parseBrlCents } from '../../../shared/finance/money';
import type { ContributionPreview, LedgerReserve, ReserveSummary } from './LedgerReserves';

interface FundingPlan { reserveId: string; suggestedCents: number | null; contributionCents: number | null; capacityCents?: number; capacityShortfallCents?: number; overdueCents?: number; behindSchedule: boolean; dates: string[]; targets: { id?: string; dueOn: string; remainingCents: number; remainingDates: number; suggestedCents: number }[] }
interface FundingEvent { id: string; reserve_id: string; scheduled_for: string; occurred_on: string; suggested_cents: number; contributed_cents: number; shortfall_cents: number; origin: string }
interface Funding { plans: FundingPlan[]; events: FundingEvent[] }
type PlannedReserve = LedgerReserve & { contribution_mode: 'automatic' | 'manual'; priority: number; alert_thresholds: number[] };
const panel = 'card p-5 dark:border-slate-800 dark:bg-slate-900', input = 'w-full field-input', primary = 'btn-primary px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50';
const field = (title: string, content: ReactNode) => <label className="grid gap-2 text-sm"><span>{title}</span>{isValidElement(content) ? cloneElement(content as ReactElement<{ 'aria-label'?: string }>, { 'aria-label': title }) : content}</label>;
const decimal = (value: number) => `${Math.floor(value / 100)},${String(value % 100).padStart(2, '0')}`;

export default function LedgerReservePlan({ workspace, money, onChanged }: { workspace: LedgerWorkspace; money: (value: number) => string; onChanged: () => Promise<void> }) {
  const [funding, setFunding] = useState<Funding | null>(null), [reserves, setReserves] = useState<PlannedReserve[]>([]), [editing, setEditing] = useState<string | null>(null), [quotas, setQuotas] = useState<{ date: string; amount: string }[]>([]), [editQuotas, setEditQuotas] = useState(false);
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState(''), [confirming, setConfirming] = useState<string | null>(null), [retry, setRetry] = useState(() => crypto.randomUUID());
  const [preview,setPreview] = useState<ContributionPreview | null>(null);
  const canManage = ['owner', 'admin'].includes(workspace.role), canWrite = workspace.role !== 'viewer';
  async function load() { const [f, r] = await Promise.all([ledgerRpc<Funding>('reserve_funding_summary', { p_space: workspace.space.id }), ledgerRpc<ReserveSummary>('reserve_summary', { p_space: workspace.space.id })]); setFunding(f); setReserves(r.reserves as PlannedReserve[]); }
  useEffect(() => { setPreview(null); void load().catch(failure => setError(failure.message)); }, [workspace]);
  async function run(name: string, args: Record<string, unknown>) { setBusy(true); setError(''); setNotice(''); try { await ledgerRpc(name, { p_space: workspace.space.id, ...args }); await load(); await onChanged(); setEditing(null); setConfirming(null); setNotice('Plano de aportes atualizado.'); } catch (failure) { setError(failure instanceof Error ? failure.message : 'Não foi possível salvar.'); } finally { setBusy(false); } }
  function openPlan(reserve: PlannedReserve) { const plan = funding?.plans.find(item => item.reserveId === reserve.id); setEditing(reserve.id); setConfirming(null); setEditQuotas(false); setQuotas(plan?.targets.map(target => ({ date: target.dueOn, amount: decimal(target.remainingCents) })) ?? []); }
  async function save(event: FormEvent<HTMLFormElement>, reserve: PlannedReserve) {
    event.preventDefault(); const form = new FormData(event.currentTarget);
    try { await run('configure_reserve_plan', { p_reserve: reserve.id, p_version: reserve.version, p_payload: { contribution_mode: String(form.get('mode')), priority: Number(form.get('priority')), alert_thresholds: String(form.get('thresholds')).split(',').map(value => Number(value.trim())).filter(value => value > 0), is_emergency_reserve: reserve.reserve_type === 'goal' && form.get('emergency') === 'on', ...(editQuotas ? { quotas: quotas.map((quota, index) => ({ title: quotas.length > 1 ? `${reserve.name} · cota ${index + 1}` : reserve.name, due_on: quota.date, amount_cents: parseBrlCents(quota.amount) })) } : {}) } }); } catch (failure) { setError((failure as Error).message); }
  }
  async function confirmCycle(event: FormEvent<HTMLFormElement>, reserve: PlannedReserve, scheduled: string) {
    event.preventDefault(); if (busy) return;
    const form = new FormData(event.currentTarget); setBusy(true); setError('');
    try {
      const amount = parseBrlCents(String(form.get('amount')));
      if (reserve.reserve_type === 'goal' && !preview) {
        const result = await ledgerRpc<ContributionPreview>('preview_reserve_contribution', { p_space: workspace.space.id, p_reserve: reserve.id, p_kind: 'contribution', p_amount_cents: amount, p_on: workspace.space.today, p_note: `Confirmação do aporte de ${scheduled}` });
        setPreview(result);
        if (result.requiresWarning) return;
      }
      await ledgerRpc('confirm_reserve_funding', { p_space: workspace.space.id, p_reserve: reserve.id, p_scheduled: scheduled, p_amount_cents: amount, p_client_uuid: retry, p_approval_token: preview?.requiresWarning && form.get('negative_ack') === 'on' ? preview.approvalToken : null });
      await load(); await onChanged(); setConfirming(null); setPreview(null); setNotice('Plano de aportes atualizado.');
    } catch (failure) { const message = failure instanceof Error ? failure.message : 'Não foi possível confirmar.'; if (message.includes('preview changed') || message.includes('free balance negative')) { setPreview(null); setError('O valor disponível mudou. Confira novamente o aporte antes de confirmar.'); } else setError(message); }
    finally { setBusy(false); }
  }
  return <section className={`${panel} space-y-5`} aria-label="Planejamento de aportes"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-semibold">Planejamento de aportes</h2><p className="mt-1 max-w-prose text-sm text-slate-500">O valor é recalculado pelas datas de renda, pelo dinheiro já reservado e por todas as cotas ainda abertas.</p></div>{canManage && <button disabled={busy} onClick={() => void run('process_reserve_funding', {})} className="text-sm font-semibold text-brand-700 dark:text-brand-300">Processar aportes vencidos</button>}</div>
    {error && <p role="alert" className="rounded-xl bg-red-50 p-4 text-sm text-red-800 dark:bg-red-950 dark:text-red-200">{error}</p>}{notice && <p role="status" className="text-sm text-brand-700 dark:text-brand-300">{notice}</p>}{!funding && !error && <p className="text-sm text-slate-500">Carregando planos…</p>}{funding?.plans.length === 0 && <p className="text-sm text-slate-500">Crie uma meta ou provisão para acompanhar seus próximos aportes.</p>}
    {funding?.plans.map(plan => { const reserve = reserves.find(item => item.id === plan.reserveId); if (!reserve) return null; const pendingDate = plan.dates.find(date => date <= workspace.space.today && !funding.events.some(event => event.reserve_id === reserve.id && event.scheduled_for === date)); return <article key={reserve.id} className="space-y-4 border-t border-slate-200 pt-4 dark:border-slate-800"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-medium">{reserve.name}</h3><p className="mt-1 text-xs text-slate-500">{reserve.contribution_mode === 'automatic' ? 'Automático: após receber a renda ou no início do ciclo' : 'Manual: você confirma cada aporte'}</p></div>{plan.suggestedCents !== null && <div className="text-right"><p className="text-xs text-slate-500">Aporte sugerido</p><strong>{money(plan.suggestedCents)}</strong></div>}</div>
      {plan.behindSchedule && <p className="text-sm text-amber-800 dark:text-amber-300">Provisão atrasada.{(plan.capacityShortfallCents ?? 0) > 0 ? ` A capacidade atual é ${money(plan.capacityCents ?? 0)}; faltam ${money(plan.capacityShortfallCents ?? 0)} neste aporte.` : ` Faltam ${money(plan.overdueCents ?? 0)} e não há data de aporte antes de pelo menos uma cota.`}</p>}
      {plan.targets.length > 0 && <details><summary className="cursor-pointer text-sm font-medium">Cotas e datas de aporte</summary><div className="mt-3 space-y-2 text-sm">{plan.targets.map((target, index) => <p key={target.id ?? index}>{target.dueOn.split('-').reverse().join('/')} · restante {money(target.remainingCents)} · {target.remainingDates} aportes antes do vencimento</p>)}<p className="text-xs text-slate-500">Datas previstas: {plan.dates.map(date => date.split('-').reverse().join('/')).join(' · ') || 'Nenhuma antes do vencimento'}.</p></div></details>}
      <div className="flex flex-wrap gap-4 text-sm font-semibold text-brand-700 dark:text-brand-300">{canManage && <button disabled={busy} onClick={() => openPlan(reserve)}>Configurar plano e cotas</button>}{canWrite && reserve.contribution_mode === 'manual' && pendingDate && <><button disabled={busy} onClick={() => { setConfirming(reserve.id); setPreview(null); setEditing(null); setRetry(crypto.randomUUID()); }}>Confirmar aporte do ciclo</button><button disabled={busy} onClick={() => void run('confirm_reserve_funding', { p_reserve: reserve.id, p_scheduled: pendingDate, p_amount_cents: 0, p_dismiss: true })}>Dispensar aporte deste ciclo</button></>}</div>
      {canWrite && confirming === reserve.id && pendingDate && <form onSubmit={event => void confirmCycle(event, reserve, pendingDate)} onChange={event => { const target = event.target; if (!(target instanceof HTMLInputElement) || target.name !== 'negative_ack') { setPreview(null); setRetry(crypto.randomUUID()); } }} className="grid max-w-xl gap-3">{field(`Valor a separar no ciclo de ${pendingDate.split('-').reverse().join('/')} (R$)`, <input name="amount" inputMode="decimal" defaultValue={decimal(plan.suggestedCents ?? 0)} required className={input}/>)}<p className="text-xs text-slate-500">Você pode ajustar o valor sugerido. Confira o Livre para gastar antes de separar dinheiro para uma meta.</p>{preview?.requiresWarning && <div role="alert" className="space-y-3 rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-900 dark:border-amber-800 dark:bg-amber-950 dark:text-amber-200"><p className="font-semibold">Este aporte deixa o Livre para gastar conservador negativo.</p><p>Antes do aporte: {money(preview.conservativeBeforeCents!)}. Após o aporte: {money(preview.conservativeAfterCents!)}.</p><label className="flex gap-2"><input key={preview.approvalToken} name="negative_ack" type="checkbox" required/>Conferi o aviso e quero manter este aporte.</label></div>}<div className="flex gap-3"><button disabled={busy} className={primary}>{preview?.requiresWarning ? 'Confirmar aporte mesmo assim' : 'Confirmar valor do aporte'}</button><button type="button" onClick={() => { setConfirming(null); setPreview(null); }}>Cancelar</button></div></form>}
      {canManage && editing === reserve.id && <form key={`${reserve.id}-${reserve.version}`} onSubmit={event => void save(event, reserve)} className="grid gap-4 sm:grid-cols-2">
        {field('Modo dos aportes', <select name="mode" defaultValue={reserve.contribution_mode} className={input}><option value="manual">Manual: confirmar, alterar ou dispensar</option><option value="automatic">Automático: executar nas datas do plano</option></select>)}{field('Prioridade do aporte (maior primeiro)', <input name="priority" type="number" min={-32768} max={32767} defaultValue={reserve.priority} required className={input}/>)}{field('Alertas de progresso (%) separados por vírgula', <input name="thresholds" defaultValue={reserve.alert_thresholds.join(',')} className={input}/>)}{reserve.reserve_type === 'goal' && <label className="flex gap-2 text-sm"><input name="emergency" type="checkbox" defaultChecked={reserve.is_emergency_reserve}/>Reserva de emergência</label>}
        {reserve.reserve_type === 'provision' && <><label className="flex gap-2 text-sm sm:col-span-2"><input type="checkbox" checked={editQuotas} onChange={event => setEditQuotas(event.target.checked)}/>Substituir o valor, as datas ou as cotas da provisão</label>{editQuotas && <div className="space-y-3 sm:col-span-2"><p className="text-xs text-slate-500">Os compromissos anteriores ficam no histórico. Cotas já pagas precisam ser resolvidas antes de substituir o plano.</p>{quotas.map((quota, index) => <div key={index} className="grid gap-3 sm:grid-cols-[1fr_1fr_auto]">{field(`Vencimento da cota ${index + 1}`, <input type="date" value={quota.date} required onChange={event => setQuotas(rows => rows.map((row, i) => i === index ? { ...row, date: event.target.value } : row))} className={input}/>)}{field(`Valor da cota ${index + 1} (R$)`, <input inputMode="decimal" value={quota.amount} required onChange={event => setQuotas(rows => rows.map((row, i) => i === index ? { ...row, amount: event.target.value } : row))} className={input}/>)}<button type="button" disabled={quotas.length < 2} onClick={() => setQuotas(rows => rows.filter((_, i) => i !== index))} className="self-end py-2 text-sm text-red-600">Remover cota</button></div>)}<button type="button" onClick={() => setQuotas(rows => [...rows, { date: reserve.target_date ?? workspace.space.today, amount: '0,00' }])} className="text-sm font-semibold text-brand-700 dark:text-brand-300">Adicionar cota</button></div>}</>}
        <div className="flex gap-3 sm:col-span-2"><button disabled={busy} className={primary}>Salvar plano de aportes</button><button type="button" onClick={() => setEditing(null)}>Cancelar</button></div>
      </form>}
      {funding.events.some(event => event.reserve_id === reserve.id) && <details><summary className="cursor-pointer text-sm font-medium">Aportes processados por ciclo</summary><div className="mt-3 space-y-2">{funding.events.filter(event => event.reserve_id === reserve.id).map(event => <p key={event.id} className="text-xs text-slate-500">Ciclo de {event.scheduled_for.split('-').reverse().join('/')} · {event.origin === 'dismissed' ? 'Dispensado' : `${money(event.contributed_cents)} em ${event.occurred_on.split('-').reverse().join('/')}`}{event.shortfall_cents > 0 ? ` · Diferença redistribuída: ${money(event.shortfall_cents)}` : ''}</p>)}</div></details>}
    </article>; })}
  </section>;
}
