import { useEffect, useState } from 'react';
import { Download, RefreshCw } from 'lucide-react';
import { ledgerRpc, type LedgerWorkspace } from '../lib/ledgerRepository';

export interface ReportItem { account_id?: string | null; transaction_id?: string; label?: string; description?: string; on?: string; month?: string; due_on?: string; original_competence_month?: string | null; class?: 'income' | 'expense'; amount_cents: number; display_amount_cents?: number; gross_cents?: number; refund_cents?: number; notes?: string; payment_names?: string[]; tags?: string[]; annual_cents?: number; next_due_on?: string | null; category?: string; payment_name?: string; unit?: string; interval_count?: number; starts_on?: string; ends_on?: string | null; versions?: { from:string; amount_cents:number; interval_count:number }[] }
export interface FutureInstallments { total_cents: number; next_cycle_cents: number; average_cents: number; income_percent: number | null; cycles: { from: string; until: string; amount_cents: number }[]; items: (ReportItem & { kind: 'card' | 'loan' })[] }
interface Reports { month: string; as_of: string; available_accounts: { id: string; name: string; archived: boolean }[]; consumption: { income_cents: number; expense_cents: number; snapshot: boolean; items: ReportItem[] }; installment_consumption: { expense_cents: number; items: ReportItem[] }; cash_flow: Flow; benefit_flow: Flow; comparison: { month: string; income_cents: number; expense_cents: number; expense_change_percent: number | null; new?:boolean; snapshot: boolean }[]; net_worth: { month: string; net_worth_cents: number; opening_cents: number; growth_cents: number; snapshot: boolean }[]; future_installments: FutureInstallments }
interface Flow { net_cents: number; opening_cents?: number; sections: Record<string, number>; items: ReportItem[] }
export interface ReportProps { workspace: LedgerWorkspace; money: (value: number) => string; privacy: boolean }
const panel = 'card p-5 dark:border-slate-800 dark:bg-slate-900';
const control = 'rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-950';
const sectionLabels: Record<string,string> = { operational:'Operacional',debts:'Empréstimos e financiamentos',investments:'Investimentos e bens',people:'Valores com pessoas' };
export const reportDate = (value: string) => value.split('-').reverse().join('/');
export const reportMonth = (value: string) => `${value.slice(5,7)}/${value.slice(0,4)}`;
export function reportPercent(value: number | null,privacy: boolean) { return privacy ? '••••' : value === null ? '—' : `${value.toLocaleString('pt-BR',{ maximumFractionDigits:1 })}%`; }

export function FutureInstallmentList({ value,money,privacy }: { value: FutureInstallments; money: ReportProps['money']; privacy: boolean }) {
  return <section className={`${panel} space-y-4`} aria-label="Parcelas futuras">
    <div><h2 className="font-semibold">Parcelas futuras</h2><p className="mt-1 text-sm text-slate-500">Compromissos dos próximos ciclos de renda. A parcela da fatura aberta já entra no Livre para gastar.</p></div>
    <dl className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[
      ['Total futuro',money(value.total_cents)],['Próximo ciclo',money(value.next_cycle_cents)],['Média de seis ciclos',money(value.average_cents)],['Da renda recorrente',reportPercent(value.income_percent,privacy)]
    ].map(([label,amount]) => <div key={label}><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-1 text-xl font-semibold">{amount}</dd></div>)}</dl>
    {value.income_percent === null && <p className="text-sm text-slate-500">O percentual precisa de pelo menos três meses completos de renda recorrente e de uma média maior que zero.</p>}
    <details className="border-t border-slate-200 pt-3 dark:border-slate-800"><summary className="cursor-pointer text-sm font-semibold">Próximos seis ciclos e suas parcelas</summary><div className="mt-4 space-y-3">
      {value.cycles.map(cycle => <div key={cycle.from} className="flex flex-wrap justify-between gap-2 text-sm"><span>De {reportDate(cycle.from)} até antes de {reportDate(cycle.until)}</span><strong>{money(cycle.amount_cents)}</strong></div>)}
      <div className="border-t border-slate-200 pt-3 dark:border-slate-800">{value.items.length === 0 ? <p className="text-sm text-slate-500">Nenhuma parcela futura neste momento.</p> : value.items.map((item,index) => <div key={`${item.transaction_id ?? item.account_id}-${index}`} className="flex flex-wrap justify-between gap-2 py-2 text-sm"><div><p>{item.label ?? 'Parcela'}</p><p className="mt-1 text-xs text-slate-500">{item.kind === 'card' ? 'Cartão' : 'Empréstimo ou financiamento'} · Vence {reportDate(item.due_on!)}</p></div><strong>{money(item.amount_cents)}</strong></div>)}</div>
    </div></details>
  </section>;
}

type View = 'consumption' | 'installment_consumption' | 'cash_flow' | 'benefit_flow' | 'subscriptions' | 'tax_deductible';
type Option = { id:string; name:string; archived:boolean };
type FilterOptions = Record<'accounts' | 'cards' | 'categories' | 'tags' | 'people',Option[]>;
interface CategorySummary { id:string; label:string; amount_cents:number; percent:number | null; transaction_count:number; children:Omit<CategorySummary,'children'>[] }
interface ReportQuery extends Flow { report:View; from_month:string; until_month:string; partial:boolean; year?:number; income_cents:number; expense_cents:number; total_cents?:number; annual_cents?:number; monthly_cents?:number; categories?: { label:string; amount_cents:number }[]; category_summary?:CategorySummary[] }
const monthShift = (value:string,count:number) => {
  const [year,month] = value.slice(0,7).split('-').map(Number);
  return new Date(Date.UTC(year,month-1+count,1)).toISOString().slice(0,10);
};
export default function LedgerReports({ workspace,money,privacy }: ReportProps) {
  const [month,setMonth] = useState(workspace.space.today.slice(0,7));
  const [account,setAccount] = useState('');
  const [view,setView] = useState<View>('consumption');
  const [data,setData] = useState<Reports | null>(null);
  const [error,setError] = useState('');
  const [retry,setRetry] = useState(0);
  const [exporting,setExporting] = useState(false);
  const [format,setFormat] = useState<'spreadsheet' | 'technical'>('spreadsheet');
  const [period,setPeriod] = useState('month');
  const [from,setFrom] = useState(workspace.space.today.slice(0,7));
  const [until,setUntil] = useState(workspace.space.today.slice(0,7));
  const [filters,setFilters] = useState<Record<string,string>>({});
  const [options,setOptions] = useState<FilterOptions | null>(null);
  const [query,setQuery] = useState<ReportQuery | null>(null);
  const currentMonth = `${workspace.space.today.slice(0,7)}-01`;
  const filterPayload: Record<string,unknown> = { ...Object.fromEntries(Object.entries(filters).filter(([,value]) => value)),account:account || null,year:Number(month.slice(0,4)) };
  if (period==='custom') { filterPayload.from_month=`${from}-01`; filterPayload.until_month=monthShift(until,1); }
  else if (period==='previous') { filterPayload.from_month=monthShift(currentMonth,-1); filterPayload.until_month=currentMonth; }
  else if (['3','6','12'].includes(period)) { filterPayload.from_month=monthShift(currentMonth,-Number(period)+1); filterPayload.until_month=monthShift(currentMonth,1); }
  else if (period==='year' || period==='previous_year') {
    const year=Number(currentMonth.slice(0,4))-(period==='previous_year' ? 1 : 0);
    filterPayload.from_month=`${year}-01-01`; filterPayload.until_month=`${year+1}-01-01`; filterPayload.year=year;
  }
  const filterKey=JSON.stringify(filterPayload);
  useEffect(() => { setMonth(workspace.space.today.slice(0,7)); setAccount(''); setFilters({}); setOptions(null); setPeriod('month'); },[workspace.space.id]);
  useEffect(() => {
    let cancelled = false;
    setData(null); setQuery(null); setError('');
    void Promise.all([
      ledgerRpc<Reports>('reports_summary',{ p_space:workspace.space.id,p_month:`${month}-01`,p_account:account || null }),
      ledgerRpc<ReportQuery>('reports_query',{ p_space:workspace.space.id,p_report:view,p_month:`${month}-01`,p_filters:JSON.parse(filterKey) }),
      ledgerRpc<FilterOptions>('report_filter_options',{ p_space:workspace.space.id }),
      ledgerRpc<Reports['comparison']>('report_comparison',{ p_space:workspace.space.id,p_month:`${month}-01`,p_filters:JSON.parse(filterKey) })
    ]).then(([summary,result,available,comparison]) => { if (!cancelled) { setData({ ...summary,comparison }); setQuery(result); setOptions(available); } }).catch(() => { if (!cancelled) setError('Não foi possível carregar os relatórios. Verifique o período, a conexão e tente novamente.'); });
    return () => { cancelled = true; };
  },[workspace,month,account,retry,view,filterKey]);
  async function download(report: string) {
    if (exporting) return;
    setExporting(true); setError('');
    try {
      const csv = report==='net_worth'
        ? await ledgerRpc<string>('export_financial_report',{ p_space:workspace.space.id,p_report:report,p_month:`${month}-01`,p_format:format,p_account:account || null })
        : await ledgerRpc<string>('export_filtered_report',{ p_space:workspace.space.id,p_report:report,p_month:`${month}-01`,p_format:format,p_filters:JSON.parse(filterKey) });
      const url = URL.createObjectURL(new Blob([csv],{ type:'text/csv;charset=utf-8' }));
      const link = document.createElement('a'); link.href=url; link.download=`financas-${report}-${month}.csv`; link.click();
      window.setTimeout(() => URL.revokeObjectURL(url),1000);
    } catch { setError('Não foi possível gerar o arquivo. Tente novamente.'); }
    finally { setExporting(false); }
  }
  const rows = query?.items ?? [];
  const accounts = options?.accounts ?? data?.available_accounts ?? workspace.accounts.map(item => ({ id:item.id,name:item.name,archived:false }));
  const titles: Record<View,string> = { consumption:'Consumo por competência',installment_consumption:'Despesas por vencimento das parcelas',cash_flow:'Fluxo de caixa',benefit_flow:'Movimentação de benefícios',subscriptions:'Assinaturas',tax_deductible:'Despesas dedutíveis no IR' };
  const notes: Record<View,string> = { consumption:'Receitas e despesas pertencem ao mês de competência. Compras parceladas entram pelo total da compra.',installment_consumption:'Cada parcela de cartão pertence ao mês do vencimento efetivo da fatura. Essa consulta preserva o consumo usado no orçamento.',cash_flow:'Movimentações de dinheiro por data financeira, classificadas pela outra ponta. Inclui o pagamento da fatura e separa investimentos, dívidas e pessoas.',benefit_flow:'Entradas e saídas de benefício por data financeira, apresentadas separadamente do dinheiro em contas.',subscriptions:'Regras de saída marcadas como assinatura, ativas ou encerradas no período. O total mensal corresponde ao total anual dividido por doze.',tax_deductible:'Lista de apoio por ano-calendário, com despesas marcadas como dedutíveis e seus reembolsos ligados. Não calcula imposto nem aplica limites legais de dedução.' };
  const flow = view === 'cash_flow' || view === 'benefit_flow' ? query : null;
  const changeFilter = (key:string,value:string) => setFilters(previous => ({ ...previous,[key]:value }));
  return <div className="space-y-5">
    <section className={panel}><div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-xl font-semibold">Relatórios</h1><p className="mt-1 text-sm text-slate-500">Veja seu consumo, seu caixa e a evolução do patrimônio.</p></div><button onClick={() => setRetry(value => value+1)} className="flex items-center gap-2 text-sm font-semibold text-brand-700 dark:text-brand-300"><RefreshCw size={16}/>Atualizar</button></div>
      <div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><label className="grid gap-1.5 text-sm">Mês<input aria-label="Mês do relatório" type="month" required max={workspace.space.today.slice(0,7)} value={month} onChange={event => { if (event.target.value) setMonth(event.target.value); }} className={control}/></label><label className="grid gap-1.5 text-sm">Conta dos lançamentos<select value={account} onChange={event => setAccount(event.target.value)} className={control}><option value="">Todas as contas</option>{accounts.map(item => <option key={item.id} value={item.id}>{item.name}{item.archived ? ' · arquivada' : ''}</option>)}</select></label><label className="grid gap-1.5 text-sm">Visão<select value={view} onChange={event => setView(event.target.value as View)} className={control}>{Object.entries(titles).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label></div>
      <div className="mt-4 grid gap-4 sm:grid-cols-3"><label className="grid gap-1.5 text-sm">Período<select value={period} onChange={event => setPeriod(event.target.value)} className={control}><option value="month">Mês escolhido</option><option value="previous">Mês anterior</option><option value="3">Últimos três meses</option><option value="6">Últimos seis meses</option><option value="12">Últimos doze meses</option><option value="year">Este ano</option><option value="previous_year">Ano anterior</option><option value="custom">Personalizado</option></select></label>{period==='custom' && <><label className="grid gap-1.5 text-sm">De<input type="month" value={from} onChange={event => { if(event.target.value) setFrom(event.target.value); }} className={control}/></label><label className="grid gap-1.5 text-sm">Até<input type="month" value={until} onChange={event => { if(event.target.value) setUntil(event.target.value); }} className={control}/></label></>}</div>
      <details className="mt-4 border-t border-slate-200 pt-3 dark:border-slate-800"><summary className="cursor-pointer text-sm font-semibold">Filtrar cartão, categoria, tag ou pessoa</summary><div className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{([
        ['card','Cartão','cards'],['category','Categoria e suas subcategorias','categories'],['tag','Tag','tags'],['person','Pessoa','people']
      ] as const).map(([key,label,source]) => <label key={key} className="grid gap-1.5 text-sm">{label}<select value={filters[key] ?? ''} onChange={event => changeFilter(key,event.target.value)} className={control}><option value="">Todos</option>{(options?.[source] ?? []).map(item => <option key={item.id} value={item.id}>{item.name}{item.archived ? ' · arquivado' : ''}</option>)}</select></label>)}<label className="grid gap-1.5 text-sm">Essenciais<select value={filters.essential ?? ''} onChange={event => changeFilter('essential',event.target.value)} className={control}><option value="">Todas as categorias</option><option value="true">Essenciais</option><option value="false">Não essenciais</option></select></label><label className="grid gap-1.5 text-sm">Tipo de despesa<select value={filters.fixity ?? ''} onChange={event => changeFilter('fixity',event.target.value)} className={control}><option value="">Fixas e variáveis</option><option value="fixed">Fixas</option><option value="variable">Variáveis</option></select></label></div><button onClick={() => { setAccount(''); setFilters({}); }} className="mt-4 text-sm font-semibold text-brand-700 dark:text-brand-300">Limpar filtros</button></details>
    </section>
    {error && <div role="alert" className="rounded-xl bg-amber-50 p-4 text-sm text-amber-800 dark:bg-amber-950 dark:text-amber-200">{error}</div>}
    {!data && !error && <p role="status" className="text-sm text-slate-500">Carregando relatórios…</p>}
    {data && query && <>
      <section className={`${panel} space-y-4`} aria-label={titles[view]}><div><h2 className="font-semibold">{titles[view]} · {view==='tax_deductible' ? query.year : `${reportMonth(query.from_month)} a ${reportMonth(monthShift(query.until_month,-1))}`}</h2><p className="mt-1 max-w-prose text-sm text-slate-500">{notes[view]}</p>{query.partial && <p className="mt-2 text-xs text-slate-500">Período parcial: os lançamentos futuros ficam fora dos valores efetivos.</p>}<details className="mt-3 text-sm text-slate-500"><summary className="cursor-pointer">Como calculamos</summary><p className="mt-2">{notes[view]} Os filtros se aplicam no servidor; estornos acompanham a compra original nos filtros de conta, cartão, tag e pessoa.</p></details></div>
        <dl className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{view === 'consumption' ? <><div><dt className="text-xs text-slate-500">Receitas</dt><dd className="mt-1 text-2xl font-semibold text-emerald-700 dark:text-emerald-300">{money(query.income_cents)}</dd></div><div><dt className="text-xs text-slate-500">Despesas</dt><dd className="mt-1 text-2xl font-semibold">{money(query.expense_cents)}</dd></div></> : view === 'installment_consumption' ? <div><dt className="text-xs text-slate-500">Despesas do período por parcela</dt><dd className="mt-1 text-2xl font-semibold">{money(query.expense_cents)}</dd></div> : view==='subscriptions' ? <><div><dt className="text-xs text-slate-500">Total mensal equivalente</dt><dd className="mt-1 text-2xl font-semibold">{money(query.monthly_cents!)}</dd></div><div><dt className="text-xs text-slate-500">Total anual</dt><dd className="mt-1 text-2xl font-semibold">{money(query.annual_cents!)}</dd></div></> : view==='tax_deductible' ? <div><dt className="text-xs text-slate-500">Despesas líquidas de reembolso</dt><dd className="mt-1 text-2xl font-semibold">{money(query.total_cents!)}</dd></div> : flow && <><div><dt className="text-xs text-slate-500">Movimentação líquida</dt><dd className="mt-1 text-2xl font-semibold">{money(flow.net_cents)}</dd></div>{Object.entries(flow.sections).map(([section,amount]) => <div key={section}><dt className="text-xs text-slate-500">{sectionLabels[section] ?? section}</dt><dd className="mt-1 text-xl font-semibold">{money(amount)}</dd></div>)}</>}</dl>
        {flow?.opening_cents !== undefined && flow.opening_cents !== 0 && <p className="text-sm text-slate-500">Saldos iniciais cadastrados no período: {money(flow.opening_cents)}.</p>}
        {view==='consumption' && !!query.category_summary?.length && <div className="space-y-3 border-t border-slate-200 pt-4 dark:border-slate-800"><h3 className="text-sm font-semibold">Despesas por categoria principal</h3>{query.category_summary.map(category => <details key={category.id} className="rounded-xl bg-slate-50 p-3 dark:bg-slate-950"><summary className="cursor-pointer text-sm"><span className="font-medium">{category.label}</span><span className="ml-3">{money(category.amount_cents)} · {reportPercent(category.percent,privacy)}</span><span className="ml-3 text-xs text-slate-500">{privacy ? '••••' : `${category.transaction_count} lançamentos`}</span></summary><div className="mt-3 space-y-2">{category.children.map(child => <div key={child.id} className="flex flex-wrap justify-between gap-2 text-sm"><span>{child.label}</span><span>{money(child.amount_cents)} · {reportPercent(child.percent,privacy)}</span></div>)}</div></details>)}</div>}
        {view==='tax_deductible' && !!query.categories?.length && <div className="grid gap-3 border-t border-slate-200 pt-4 sm:grid-cols-2 dark:border-slate-800">{query.categories.map(category => <div key={category.label} className="flex flex-wrap justify-between gap-2 text-sm"><span>{category.label}</span><strong>{money(category.amount_cents)}</strong></div>)}</div>}
        <div className="border-t border-slate-200 pt-3 dark:border-slate-800">{rows.length === 0 ? <p className="text-sm text-slate-500">Nenhuma movimentação nesta visão para o período e os filtros selecionados.</p> : rows.map((item,index) => <div key={`${item.transaction_id ?? item.account_id}-${index}`} className="border-b border-slate-100 py-3 text-sm last:border-0 dark:border-slate-800"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="font-medium">{item.label ?? item.description ?? 'Movimentação'}</p><p className="mt-1 text-xs text-slate-500">{view==='subscriptions' ? `${item.category ?? 'Sem categoria'} · A cada ${item.interval_count} ${item.unit==='month' ? 'mês(es)' : item.unit==='week' ? 'semana(s)' : 'ano(s)'} · ${item.payment_name ?? 'Meio de pagamento'}` : item.class === 'income' ? 'Receita' : item.class === 'expense' ? 'Despesa' : item.on ? reportDate(item.on) : 'Despesa por parcela'}{item.original_competence_month ? ` · ref. ${reportMonth(item.original_competence_month)}` : ''}{item.description ? ` · ${item.description}` : ''}</p></div><strong>{money(item.display_amount_cents ?? item.amount_cents)}</strong></div>
          {view==='tax_deductible' && <div className="mt-3 space-y-1 text-xs text-slate-500"><p>Valor original: {money(item.gross_cents!)} · Reembolso: {money(item.refund_cents!)} · Líquido: {money(item.amount_cents)}</p><p>{item.payment_names?.join(', ')}{item.tags?.length ? ` · ${item.tags.join(', ')}` : ''}</p>{item.notes && <p>Observação: {item.notes}</p>}</div>}
          {view==='subscriptions' && <div className="mt-3 space-y-2 text-xs text-slate-500"><p>Anual: {money(item.annual_cents!)} · Início: {reportDate(item.starts_on!)}{item.ends_on ? ` · Encerramento: ${reportDate(item.ends_on)}` : ''} · {item.next_due_on ? `Próxima cobrança: ${reportDate(item.next_due_on)}` : 'Sem próxima cobrança em aberto'}</p><details><summary className="cursor-pointer">Histórico de valores</summary><div className="mt-2 space-y-1">{item.versions?.map(version => <p key={version.from}>A partir de {reportDate(version.from)}: {money(version.amount_cents)}</p>)}</div></details></div>}
        </div>)}</div>
        <div className="flex flex-wrap items-end gap-3 border-t border-slate-200 pt-3 dark:border-slate-800"><label className="grid gap-1.5 text-sm">Formato do arquivo<select value={format} onChange={event => setFormat(event.target.value as typeof format)} className={control}><option value="spreadsheet">Planilha · valores em reais</option><option value="technical">Dados · valores em centavos</option></select></label><button disabled={exporting} onClick={() => void download(view)} className="flex items-center gap-2 rounded-xl bg-brand-700 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50"><Download size={16}/>{exporting ? 'Gerando arquivo…' : 'Baixar CSV'}</button>{privacy && <p className="text-xs text-slate-500">O arquivo contém os valores completos.</p>}</div>
      </section>
      <section className={`${panel} space-y-4`}><h2 className="font-semibold">Comparação dos últimos seis meses</h2><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-xs text-slate-500"><th className="py-2 pr-4">Mês</th><th className="py-2 pr-4">Receitas</th><th className="py-2 pr-4">Despesas</th><th className="py-2">Variação das despesas</th></tr></thead><tbody>{data.comparison.map(item => <tr key={item.month} className="border-t border-slate-100 dark:border-slate-800"><td className="whitespace-nowrap py-3 pr-4">{reportMonth(item.month)}{item.snapshot ? ' · fechado' : ''}</td><td className="whitespace-nowrap pr-4">{money(item.income_cents)}</td><td className="whitespace-nowrap pr-4">{money(item.expense_cents)}</td><td>{!privacy && item.new ? 'Novo' : reportPercent(item.expense_change_percent,privacy)}</td></tr>)}</tbody></table></div></section>
      <section className={`${panel} space-y-4`}><div className="flex flex-wrap justify-between gap-2"><div><h2 className="font-semibold">Patrimônio do espaço</h2><p className="mt-1 text-sm text-slate-500">Valores no fim de cada mês. Meses fechados usam seu retrato preservado.</p></div><button disabled={exporting} onClick={() => void download('net_worth')} className="text-sm font-semibold text-brand-700 dark:text-brand-300">Baixar CSV</button></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-xs text-slate-500"><th className="py-2 pr-4">Mês</th><th className="py-2 pr-4">Patrimônio líquido</th><th className="py-2 pr-4">Variação da atividade</th><th className="py-2">Saldos iniciais cadastrados</th></tr></thead><tbody>{data.net_worth.map(item => <tr key={item.month} className="border-t border-slate-100 dark:border-slate-800"><td className="whitespace-nowrap py-3 pr-4">{reportMonth(item.month)}{item.snapshot ? ' · fechado' : ''}</td><td className="whitespace-nowrap pr-4 font-semibold">{money(item.net_worth_cents)}</td><td className="whitespace-nowrap pr-4">{money(item.growth_cents)}</td><td className="whitespace-nowrap">{money(item.opening_cents)}</td></tr>)}</tbody></table></div></section>
      <FutureInstallmentList value={data.future_installments} money={money} privacy={privacy}/>
    </>}
  </div>;
}
