import { cloneElement, isValidElement, useEffect, useState, type ReactElement, type FormEvent, type ReactNode } from 'react';
import { ledgerRpc, type LedgerWorkspace } from '../lib/ledgerRepository';
import { parseBrlCents } from '../../../shared/finance/money';

interface AgendaItem { id: string; type: string; title: string; on: string; nominal_due_on?: string; competence_month?: string; due_amount_cents?: number; remaining_cents: number | null; paid_cents?: number; direction: string | null; certainty?: string; settlement_status: string; version: number; category_id?: string | null; category_name?: string; notes?: string | null; payment_name?: string; payment_method?: string; payment_financial_account_id?: string; payment_credit_card_id?: string; loan_installment?: boolean; reserve_id?: string; recurrence_rule_id?: string }
interface Calendar { month: string; today: string; items: AgendaItem[] }
const input = 'w-full field-input px-3 py-2.5 dark:border-slate-700 dark:bg-slate-800';
const panel = 'card p-5 dark:border-slate-800 dark:bg-slate-900';
const primary = 'btn-primary px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50';
const field = (name: string, content: ReactNode) => <label className="grid gap-2 text-sm"><span>{name}</span>{isValidElement(content) ? cloneElement(content as ReactElement<{ 'aria-label'?: string }>, { 'aria-label': name }) : content}</label>;
const decimal = (value: number) => `${Math.floor(value / 100)},${String(value % 100).padStart(2, '0')}`;
const statuses: Record<string, string> = { settled: 'Concluído', cancelled: 'Cancelado', partial: 'Parcial', pending: 'Pendente', scheduled: 'Agendado' };

export default function LedgerAgenda({ workspace, money, onChanged }: { workspace: LedgerWorkspace; money: (value: number) => string; onChanged: () => Promise<void> }) {
  const [month, setMonth] = useState(workspace.space.today.slice(0, 7)), [calendar, setCalendar] = useState<Calendar | null>(null), [day, setDay] = useState(''), [status, setStatus] = useState('open');
  const [action, setAction] = useState<{ id: string; type: 'pay' | 'edit' | 'cancel' } | null>(null), [method, setMethod] = useState('account'), [retry, setRetry] = useState(() => crypto.randomUUID());
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState('');
  const canWrite = workspace.role !== 'viewer';
  async function load() { setCalendar(await ledgerRpc<Calendar>('agenda_month', { p_space: workspace.space.id, p_month: `${month}-01` })); }
  useEffect(() => { let active = true; setCalendar(previous => previous?.month === `${month}-01` ? previous : null); void ledgerRpc<Calendar>('agenda_month', { p_space: workspace.space.id, p_month: `${month}-01` }).then(next => { if (active) setCalendar(next); }).catch(failure => { if (active) setError(failure.message); }); return () => { active = false; }; }, [workspace, month]);
  async function run(name: string, args: Record<string, unknown>) {
    setBusy(true); setError(''); setNotice('');
    try { await ledgerRpc(name, { p_space: workspace.space.id, ...args }); await load(); await onChanged(); setAction(null); setNotice('Agenda atualizada.'); }
    catch (failure) { setError(failure instanceof Error ? failure.message : 'Não foi possível salvar.'); }
    finally { setBusy(false); }
  }
  function choose(item: AgendaItem, type: 'pay' | 'edit' | 'cancel') { setAction({ id: item.id, type }); setMethod(item.payment_method ?? 'account'); setRetry(crypto.randomUUID()); setError(''); setNotice(''); }
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const item = calendar?.items.find(row => row.id === action?.id); if (!item || !action || busy) return;
    const form = new FormData(event.currentTarget), text = (key: string) => String(form.get(key) ?? '').trim();
    try {
      if (action.type === 'pay') await run('settle_commitment', { p_commitment: item.id, p_amount_cents: parseBrlCents(text('amount')), p_on: text('date'), p_mode: text('mode'), p_client_uuid: retry });
      else if (action.type === 'cancel') await run('cancel_commitment', { p_commitment: item.id, p_version: item.version, p_reason: text('reason') });
      else await run('edit_commitment', { p_commitment: item.id, p_version: item.version, p_changes: { title: text('title'), notes: text('notes') || null, ...(item.type === 'reminder' || item.loan_installment || item.reserve_id || (item.paid_cents ?? 0) > 0 ? {} : { amount_cents: parseBrlCents(text('amount')), due_on: text('date'), competence_month: `${text('competence')}-01`, certainty: text('certainty'), category_id: text('category') || null, payment_method: method, payment_financial_account_id: method === 'account' ? text('account') : null, payment_credit_card_id: method === 'card' ? text('card') : null }) } });
    } catch (failure) { setError(failure instanceof Error ? failure.message : 'Confira os campos.'); }
  }
  const selected = calendar?.items.find(item => item.id === action?.id);
  const items = calendar?.items.filter(item => (!day || item.on === day) && (status === 'all' || status === 'settled' ? status === 'all' || item.settlement_status === 'settled' : ['pending', 'partial', 'scheduled'].includes(item.settlement_status))) ?? [];
  const [year, monthNumber] = month.split('-').map(Number), firstDay = (new Date(Date.UTC(year, monthNumber - 1, 1)).getUTCDay() + 6) % 7, days = new Date(Date.UTC(year, monthNumber, 0)).getUTCDate();
  const grouped = new Map<string, AgendaItem[]>(); for (const item of calendar?.items ?? []) if (item.settlement_status !== 'cancelled') grouped.set(item.on, [...(grouped.get(item.on) ?? []), item]);
  return <div className="space-y-4">
    {error && <p role="alert" className="rounded-xl border border-red-300 bg-red-50 p-4 text-sm text-red-800 dark:bg-red-950 dark:text-red-200">{error}</p>}{notice && <p role="status" className="text-sm text-brand-700 dark:text-brand-300">{notice}</p>}
    <section className={`${panel} space-y-4`}><div className="flex flex-wrap items-end gap-4">{field('Mês da Agenda', <input type="month" value={month} onChange={event => { if (event.target.value) { setMonth(event.target.value); setDay(''); setAction(null); setError(''); } }} required className={input}/>)}{field('Situação', <select value={status} onChange={event => setStatus(event.target.value)} className={input}><option value="open">Pendentes e agendados</option><option value="settled">Concluídos</option><option value="all">Todos</option></select>)}<button onClick={() => setDay('')} className="text-sm font-semibold text-brand-700 dark:text-brand-300">Ver o mês inteiro</button></div>
      <div className="grid grid-cols-7 gap-1 text-center text-xs">{['Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb', 'Dom'].map(label => <span key={label} className="py-2 text-slate-500">{label}</span>)}{Array.from({ length: firstDay }, (_, index) => <span key={`blank-${index}`}/>)}{Array.from({ length: days }, (_, index) => { const on = `${month}-${String(index + 1).padStart(2, '0')}`, rows = grouped.get(on) ?? [], overdue = rows.some(item => ['pending', 'partial'].includes(item.settlement_status) && on < workspace.space.today); return <button key={on} aria-label={`${index + 1}: ${rows.length} itens`} aria-pressed={day === on} onClick={() => setDay(day === on ? '' : on)} className={`min-h-16 rounded-lg border p-1 sm:min-h-20 ${day === on ? 'border-brand-600 bg-brand-50 dark:bg-brand-950' : 'border-slate-200 dark:border-slate-800'} ${on === workspace.space.today ? 'font-bold ring-1 ring-brand-500' : ''}`}><span>{index + 1}</span>{rows.length > 0 && <span className={`mt-2 block rounded-full px-1 py-0.5 text-[10px] ${overdue ? 'bg-red-100 text-red-800 dark:bg-red-950 dark:text-red-200' : 'bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-300'}`}>{rows.length} {rows.length === 1 ? 'item' : 'itens'}</span>}</button>; })}</div>
      <p className="text-xs text-slate-500">O calendário reúne compromissos, lembretes, faturas e lançamentos com data futura. Selecione um dia para ver os detalhes.</p>
    </section>
    {canWrite && action && selected && <form key={`${selected.id}-${action.type}`} onSubmit={event => void submit(event)} className={`${panel} grid gap-4 sm:grid-cols-2`} onChange={() => setRetry(crypto.randomUUID())}>
      <h2 className="font-semibold sm:col-span-2">{action.type === 'pay' ? selected.direction === 'inflow' ? 'Registrar recebimento' : 'Registrar pagamento' : action.type === 'edit' ? 'Editar somente este item' : 'Cancelar compromisso'}: {selected.title}</h2>
      {action.type === 'pay' && <>{field('Valor recebido ou pago (R$)', <input name="amount" inputMode="decimal" defaultValue={decimal(selected.remaining_cents ?? 0)} required className={input}/>)}{field('Data da movimentação', <input name="date" type="date" defaultValue={workspace.space.today} required className={input}/>)}{field('Como tratar a diferença', <select name="mode" className={input}><option value="partial">Pagamento parcial: manter o restante em aberto</option>{!selected.loan_installment && <><option value="match_actual">Quitar: confirmar este como o valor real</option><option value="automatic">Aplicar a regra do valor estimado</option></>}</select>)}<p className="text-sm text-slate-500">Conta de pagamento: {selected.payment_name ?? 'Configurada no compromisso'}. Para escolher outra conta, edite o item antes de pagar.</p></>}
      {action.type === 'cancel' && <>{field('Motivo do cancelamento', <textarea name="reason" required maxLength={1000} className={input}/>)}<p className="text-sm text-slate-500">O compromisso fica preservado no histórico. Pagamentos vinculados precisam ser cancelados antes.</p></>}
      {action.type === 'edit' && <>{field('Descrição do item', <input name="title" defaultValue={selected.title} maxLength={100} required className={input}/>)}{field('Observações', <textarea name="notes" defaultValue={selected.notes ?? ''} maxLength={1000} className={input}/>)}{selected.type !== 'reminder' && !selected.loan_installment && !selected.reserve_id && !(selected.paid_cents! > 0) ? <>
        {field('Valor previsto (R$)', <input name="amount" defaultValue={decimal(selected.due_amount_cents ?? 0)} inputMode="decimal" required className={input}/>)}{field('Vencimento nominal', <input name="date" type="date" defaultValue={selected.nominal_due_on ?? selected.on} required className={input}/>)}{field('Mês de competência', <input name="competence" type="month" defaultValue={selected.competence_month?.slice(0, 7) ?? month} required className={input}/>)}{field('Certeza do valor', <select name="certainty" defaultValue={selected.certainty} className={input}><option value="confirmed">Confirmado</option><option value="estimated">Estimado</option>{selected.direction === 'inflow' && <option value="conditional">Condicional</option>}</select>)}
        {field('Categoria deste item', <select name="category" defaultValue={selected.category_id ?? ''} className={input}><option value="">Manter a contrapartida atual</option>{workspace.categories.filter(category => category.ledger_account_id && category.kind === (selected.direction === 'inflow' ? 'income' : 'expense')).map(category => <option key={category.id} value={category.id}>{category.name}</option>)}</select>)}{field('Meio de pagamento', <select value={method} onChange={event => setMethod(event.target.value)} className={input}><option value="account">Conta</option>{selected.direction !== 'inflow' && <option value="card">Cartão</option>}</select>)}
        {method === 'account' ? field('Conta para o item', <select name="account" defaultValue={selected.payment_financial_account_id} required className={input}>{workspace.accounts.map(account => <option key={account.id} value={account.id}>{account.name}</option>)}</select>) : field('Cartão para o item', <select name="card" defaultValue={selected.payment_credit_card_id} required className={input}>{workspace.cards.map(card => <option key={card.id} value={card.id}>{card.name}</option>)}</select>)}
      </> : <p className="text-sm text-slate-500 sm:col-span-2">{selected.loan_installment ? 'A data e os valores desta parcela são corrigidos no cronograma do empréstimo, em Patrimônio.' : selected.reserve_id ? 'A data e o valor são corrigidos na provisão vinculada.' : selected.type === 'reminder' ? 'Este lembrete não gera movimentação financeira.' : 'Para mudar os termos financeiros, cancele primeiro os pagamentos vinculados.'}</p>}</>}
      <div className="flex gap-3 sm:col-span-2"><button disabled={busy} className={primary}>{busy ? 'Salvando…' : 'Confirmar'}</button><button type="button" onClick={() => setAction(null)}>Voltar à Agenda</button></div>
    </form>}
    <section className={`${panel} space-y-4`}><h2 className="font-semibold">{day ? `Itens de ${day.split('-').reverse().join('/')}` : 'Itens do mês'}</h2>{!calendar && <p className="text-sm text-slate-500">Carregando calendário…</p>}{calendar && items.length === 0 && <p className="text-sm text-slate-500">Nenhum item para este período e situação.</p>}{items.map(item => <article key={`${item.type}-${item.id}`} className="space-y-3 border-b border-slate-100 pb-4 last:border-0 dark:border-slate-800"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-medium">{item.title}</h3><p className="mt-1 text-xs text-slate-500">{item.on.split('-').reverse().join('/')} · {statuses[item.settlement_status] ?? item.settlement_status}{['pending', 'partial'].includes(item.settlement_status) && item.on < workspace.space.today ? ' · Vencido' : ''}{item.category_name ? ` · ${item.category_name}` : ''}{item.payment_name ? ` · ${item.payment_name}` : ''}</p></div>{item.remaining_cents !== null && <strong className="text-sm">{item.direction === 'inflow' ? 'A receber: ' : 'A pagar: '}{money(item.remaining_cents ?? 0)}</strong>}</div>
      {item.type === 'card_statement' && <p className="text-xs text-slate-500">Pagamento e detalhes da fatura estão em Cartões.</p>}{item.type === 'scheduled_transaction' && <p className="text-xs text-slate-500">Movimentação registrada com data futura. Consulte os detalhes em Lançamentos.</p>}
      {canWrite && ['one_off', 'occurrence', 'reminder'].includes(item.type) && item.settlement_status !== 'cancelled' && <div className="flex flex-wrap gap-4 text-sm font-semibold text-brand-700 dark:text-brand-300">{item.type === 'reminder' ? <button disabled={busy} onClick={() => void run('complete_reminder', { p_commitment: item.id, p_version: item.version, p_completed: item.settlement_status !== 'settled' })}>{item.settlement_status === 'settled' ? 'Reabrir lembrete' : 'Concluir lembrete'}</button> : ['pending', 'partial'].includes(item.settlement_status) && <><button disabled={busy} onClick={() => void run('settle_commitment', { p_commitment: item.id, p_amount_cents: item.remaining_cents, p_on: workspace.space.today, p_client_uuid: crypto.randomUUID() })}>{item.direction === 'inflow' ? 'Registrar recebimento integral' : 'Registrar pagamento integral'}</button><button disabled={busy} onClick={() => choose(item, 'pay')}>Informar valor e data</button></>}<button disabled={busy} onClick={() => choose(item, 'edit')}>Editar este item</button>{!item.loan_installment && <button disabled={busy} onClick={() => choose(item, 'cancel')} className="text-red-600">Cancelar item</button>}</div>}
    </article>)}</section>
  </div>;
}
