import { cloneElement, isValidElement, useEffect, useState, type ReactElement, type ReactNode } from 'react';
import { ledgerRpc, type LedgerBudget, type LedgerWorkspace } from '../lib/ledgerRepository';
import { parseBrlCents } from '../../../shared/finance/money';

interface BudgetPlan { id: string; category_name: string; amount_cents: number; effective_from_month: string; effective_until_month: string | null; is_essential_override: boolean | null; version: number }
interface BudgetManagement { budgets: BudgetPlan[]; summary: LedgerBudget[] }
const panel = 'card p-5 dark:border-slate-800 dark:bg-slate-900', input = 'w-full field-input';
const field = (title: string, content: ReactNode) => <label className="grid gap-2 text-sm"><span>{title}</span>{isValidElement(content) ? cloneElement(content as ReactElement<{ 'aria-label'?: string }>, { 'aria-label': title }) : content}</label>;
export default function LedgerBudgets({ workspace, money, onChanged }: { workspace: LedgerWorkspace; money: (value: number) => string; onChanged: () => Promise<void> }) {
  const [month, setMonth] = useState(workspace.space.today.slice(0, 7)), [data, setData] = useState<BudgetManagement | null>(null), [editing, setEditing] = useState<string | null>(null), [action, setAction] = useState('month');
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState(''), [history, setHistory] = useState(false);
  const canManage = ['owner', 'admin'].includes(workspace.role);
  async function load() { setData(await ledgerRpc('budget_management_summary', { p_space: workspace.space.id, p_month: `${month}-01` })); }
  useEffect(() => { void load().catch(failure => setError(failure.message)); }, [workspace, month]);
  return <div className="space-y-4"><div className="flex flex-wrap items-end gap-4">{field('Mês dos orçamentos', <input type="month" value={month} onChange={event => { if (event.target.value) { setMonth(event.target.value); setEditing(null); } }} required className={input}/>)}<label className="flex gap-2 py-2 text-sm"><input type="checkbox" checked={history} onChange={event => setHistory(event.target.checked)}/>Mostrar todos os planos, incluindo encerrados</label></div>
    {error && <p role="alert" className="rounded-xl bg-red-50 p-4 text-sm text-red-800 dark:bg-red-950 dark:text-red-200">{error}</p>}{notice && <p role="status" className="text-sm text-teal-700 dark:text-teal-300">{notice}</p>}{!data && !error && <p className={panel}>Carregando orçamentos…</p>}
    {data?.budgets.filter(budget => history || budget.effective_from_month <= `${month}-01` && (!budget.effective_until_month || budget.effective_until_month >= `${month}-01`)).map(budget => { const summary = data.summary.find(item => item.id === budget.id); return <section key={`${budget.id}-${budget.version}`} className={`${panel} space-y-4`}><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold">{budget.category_name ?? 'Fluxo mensal'}</h2><p className="mt-1 text-xs text-slate-500">Desde {budget.effective_from_month.slice(0, 7)}{budget.effective_until_month ? ` até ${budget.effective_until_month.slice(0, 7)}` : ' · Em andamento'}</p>{summary && <p className="mt-2 text-sm text-slate-500">Gasto: {money(summary.consumed_cents)} · Previsto: {money(summary.predicted_cents)}</p>}</div><strong className="text-sm">{summary ? `Restante: ${money(summary.remaining_cents)}` : `Limite: ${money(budget.amount_cents)}`}</strong></div>
      {canManage && <button disabled={busy} onClick={() => { setEditing(editing === budget.id ? null : budget.id); setAction('month'); setError(''); }} className="text-sm font-semibold text-teal-700 dark:text-teal-300">Ajustar ou encerrar orçamento</button>}
      {canManage && editing === budget.id && <form onSubmit={async event => { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); setError(''); setNotice(''); try { await ledgerRpc('manage_budget', { p_space: workspace.space.id, p_budget: budget.id, p_version: budget.version, p_action: action, p_month: `${String(form.get('month'))}-01`, p_amount_cents: action === 'end' ? null : parseBrlCents(String(form.get('amount'))), p_essential: form.get('essential') === 'inherit' ? null : form.get('essential') === 'yes' }); await load(); await onChanged(); setEditing(null); setNotice('Orçamento atualizado.'); } catch (failure) { setError(failure instanceof Error ? failure.message : 'Não foi possível salvar.'); } finally { setBusy(false); } }} className="grid gap-4 sm:grid-cols-2">{field('Como aplicar o ajuste', <select value={action} onChange={event => setAction(event.target.value)} className={input}><option value="month">Apenas um mês</option><option value="following">Este mês e os seguintes</option><option value="end">Encerrar após o mês escolhido</option></select>)}{field('Mês do ajuste', <input name="month" type="month" defaultValue={month < budget.effective_from_month.slice(0, 7) ? budget.effective_from_month.slice(0, 7) : month} min={budget.effective_from_month.slice(0, 7)} max={budget.effective_until_month?.slice(0, 7)} required className={input}/>)}{action !== 'end' && field('Novo limite (R$)', <input name="amount" inputMode="decimal" defaultValue={`${Math.floor((summary?.amount_cents ?? budget.amount_cents) / 100)},${String((summary?.amount_cents ?? budget.amount_cents) % 100).padStart(2, '0')}`} required className={input}/>)}{action === 'following' && field('Essencial neste plano', <select name="essential" defaultValue={budget.is_essential_override === null ? 'inherit' : budget.is_essential_override ? 'yes' : 'no'} className={input}><option value="inherit">Seguir a categoria</option><option value="yes">Sim</option><option value="no">Não</option></select>)}<p className="text-xs text-slate-500 sm:col-span-2">O ajuste contínuo preserva os meses anteriores. Ajustes específicos de um mês continuam valendo até você substituí-los. Meses fechados afetados precisam ser reabertos.</p><div className="flex gap-3 sm:col-span-2"><button disabled={busy} className="btn-primary px-4 py-2.5 text-sm font-semibold text-white">Salvar ajuste do orçamento</button><button type="button" onClick={() => setEditing(null)}>Cancelar</button></div></form>}
    </section>; })}
    {data && data.budgets.length === 0 && <p className={`${panel} text-sm text-slate-500`}>Nenhum orçamento. Use Cadastrar e escolha uma categoria de despesa ou um grupo.</p>}
  </div>;
}
